### ISSUE TITLE
Occasionally get access denied error when moving files on Windows

### ISSUE THREAD

**Issue by philipstarkey** [chrisjbillington/hg-export-tool#4] opened 2020-03-09 02:42 UTC
Sometimes I get an error like this. It's probably not worth fixing (and will be very hard to debug) but I'm logging it here in case other people run into the same issue.

The solution is just to run the script again (I usually delete the converted repository named just in case it didn't complete the copy from temp to final destination).

As it's a transitory error it's probably some sort of race condition...maybe between the subprocess actually cleaning up and deleting the files? It's possible that Python gets the return code of the subprocess call before cleanup is complete (and the lock on the files in the temp directory is not released until cleanup is complete). Just a wild guess.

```
Traceback (most recent call last):
  File "exporter.py", line 245, in <module>
    main()
  File "exporter.py", line 241, in main
    BASH
  File "exporter.py", line 172, in process_repo
    shutil.move(temp_git_repo, git_repo)
  File "C:\Anaconda3\envs\py2.7\lib\shutil.py", line 323, in move
    rmtree(src)
  File "C:\Anaconda3\envs\py2.7\lib\shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Anaconda3\envs\py2.7\lib\shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Anaconda3\envs\py2.7\lib\shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Anaconda3\envs\py2.7\lib\shutil.py", line 275, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Anaconda3\envs\py2.7\lib\shutil.py", line 273, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: u'c:\\users\\user\\appdata\\local\\temp\\dihm-labscript_devices--forked-from--labscript_suite-labscript_devices-7512bae620021e4e5759eadb050ad1e3\\.git\\objects\\pack\\pack-2f56ebf337c5b522cac31c8e93762f2509025fef.idx'
```

**Comment by chrisjbillington** [comment] 2020-03-09 02:54
Oh, that's interesting. Actually I got these errors too when testing - though I thought they happened consistently. The cause seemed to be that the files were read only, and apparently you can't delete files that are read-only. Solution (I thought) was to move them instead of copy+delete. But I see in your traceback that `shutil.move` is actually implemented as copy + delete, so I guess that made no difference (though it seemed to stop the error happening for me, though if it's racy it could have been because it changed the timing of things).

Solution suggested elsewhere was to attach an error handler to `shutil.rmtree` that changes the file permissions of the file, then deleted it. I'll give that a go (tomorrow, maybe).

Not sure why the issue would be intermittent, maybe the read-only status of the file (or existence of the file) is changing in a racy way.

**Comment by philipstarkey** [comment] 2020-03-09 02:59
It may actually be certain repositories... dihm/labscript_devices and labscript_suite/opalkellyxem3001 seem the most likely to have issues (it happened again a few minutes ago and happened the other day too). But in each case deleting the converted repository in the final destination directory (I think the temp directory is deleted on exit of the Python program? I'm not touching it anyway) and re-running the script works every time.

**Comment by chrisjbillington** [comment] 2020-03-09 03:49
No, the git temp directory isn't deleted at exit - it's supposed to be moved, but since that's failing I would guess it is leaving tempfiles behind. But the temporary directories have random suffixes so shouldn't interfere with each other at least.

**Comment by philipstarkey** [comment] 2020-03-09 06:30
You are right. I had noticed the temp dirs for the hg repos were being deleted even though it was crashing out in issue #3 and had assumed the same was happening here.

That also means that I was wrong with it happening for certain repositories more frequently (as I can now check which folders still exist in temp). It's happened 4 times for me in 280 conversion and there were no repeats (converted the same 140 repositories twice).

**Comment by chrisjbillington** [comment] 2020-03-09 19:55
Should be fixed!

**Closed as completed by chrisjbillington** 2020-03-09 19:55 UTC
